[package]
name = "git-mirror"
version = "0.4.3"
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
url = "2"
which = "4"
anyhow = "1"
owo-colors = "3"
dirs = "4"
dialoguer = "0.10"
